# Generated by Django 3.1.7 on 2021-03-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('bus_type', models.CharField(choices=[(1, 'Comum'), (2, 'Executivo')], max_length=1)),
                ('destiny_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_region', to='app.region')),
                ('origin_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_region', to='app.region')),
                ('ticket_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticketbus')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='app.region')),
            ],
        ),
    ]
