# Generated by Django 3.1.7 on 2021-03-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='ticket_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bus', to='app.ticketbus'),
        ),
    ]
